version: "3.8"

services:
  mongodb:
    image: bitnami/mongodb:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=rootpassword
      - MONGODB_DATABASE=sweet_shop
      - MONGODB_USERNAME=root
    networks:
      - mongo-network
    ports:
      - 27017:27017

  backend:
    build:
      context: ./server
    container_name: backend
    depends_on:
      - mongodb
    networks:
      - mongo-network
    ports:
      - 8000:8000
    environment:
      - MONGO_DB=sweet_shop
      - MONGO_URI=mongodb://root:rootpassword@localhost:27017/sweet_shop?authSource=admin
      - SECRET_KEY="lypLIAu/gFNS0TzpKZQ4jXjBXOgNbxasgMCUfucJiaM="
      - ALGORITHM="HS256"
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

  frontend:
    build:
      context: ./client
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 3000:3000

networks:
  mongo-network:
    driver: bridge
